### ISSUE TITLE
KeyError: 'Realtime Currency Exchange Rate'

### ISSUE THREAD

**Issue by ponchik69** [b-harvest/terra_oracle_voter#18]
Sometimes the script sends exchange rate: `-1` and in log I get this:
`Traceback (most recent call last):`
 `    File "/opt/oracle/terra_oracle_voter/terra_oracle_vote.py", line 288, in get_fx_rate`
 `   api_result[list_number]["Realtime Currency Exchange Rate"]["5. Exchange Rate"])`
 `KeyError: 'Realtime Currency Exchange Rate'`

I added a `print(api_result[list_number])` and get this:
https://pastebin.com/GZP77zid
I also changed keys for alphavantage but the result doesn't change.

**Comment by nodebreaker0-0** [comment]
https://github.com/b-harvest/terra_oracle_voter/blob/master/al_api_test.py

Could you check the response value again through the script?

And sometimes there is a problem that the key is not responding due to an error in alphavantage.

**Comment by nodebreaker0-0** [comment]
Check the api, there are two types of error.

I used free-api to exceed the api call or
Incorrect key entered or
