### ISSUE TITLE
wrong telegram sendMessage URL

### ISSUE THREAD

**Issue by westaking** [b-harvest/terra_oracle_voter#9]
https://github.com/b-harvest/terra_oracle_voter/blob/a4f0a2d08c9ad664f625257088e292f42f8a9bb2/terra_oracle_vote.py#L119

https://api.telegram.org/bot/{}/sendMessage".format(telegram_token),
-->
https://api.telegram.org/bot{}/sendMessage".format(telegram_token),

need to remove / after "https://api.telegram.org/bot"

**Comment by nodebreaker0-0** [comment]
Thank you. That's reflected.
